---
ğŸ’š github_actions:
  - .github/**/*
ğŸ’š github:
  - .gitpod.yml
  - .gitconfig
  - .gitignore
  - .gitattributes
ğŸ’š husky:
  - .husky/*
ğŸ“š documentation:
  - README.md
  - .github/*/**.md
  - .github/**.md
  - LICENSE
  - rfcs/*.md
  - rfcs/*/*.md
ğŸ³ docker:
  - .devcontainer/*
  - .dockerignore
ğŸ¤– renovate_config:
  - renovate.json
ğŸ¤– dependabot_config:
  - .github/dependabot.yml
ğŸ editor_config:
  - .editorconfig
ğŸ eslint:
  - .eslintrc.js
ğŸ prettier:
  - .prettierrc
ğŸ vscode:
  - .vscode/*.json
